/*
 *  SFToSpr - Star Fighter 3000 graphics converter
 *  Error declarations
 *  Copyright (C) 2020 Christopher Bazley
 */

DECLARE_ERROR(OK)
DECLARE_ERROR(OSError)
DECLARE_ERROR(OpenInFail)
DECLARE_ERROR(OpenOutFail)
DECLARE_ERROR(ReadFail)
DECLARE_ERROR(WriteFail)
DECLARE_ERROR(BadTell)
DECLARE_ERROR(BadSeek)
DECLARE_ERROR(Trunc)
DECLARE_ERROR(TooLong)
DECLARE_ERROR(Escape)
DECLARE_ERROR(NoMem)
DECLARE_ERROR(BadDataOff)
DECLARE_ERROR(BadNumGFX)
DECLARE_ERROR(BadImages)
DECLARE_ERROR(BadPaintOff)
DECLARE_ERROR(BadAnims)
DECLARE_ERROR(ForceAnim)
DECLARE_ERROR(ForceOff)
DECLARE_ERROR(BadRend)
DECLARE_ERROR(BadStar)
DECLARE_ERROR(ForceSky)
DECLARE_ERROR(TooShort)
DECLARE_ERROR(BadSprite)

DECLARE_ERROR(NoAnim)
DECLARE_ERROR(NoHeight)
DECLARE_ERROR(NoOffset)

DECLARE_ERROR(StrOFlo)
DECLARE_ERROR(Done)
