SDCC ?= sdcc

COMMON_FLAGS = --std-c99

include MakeCommon

OBJS = $(addsuffix .rel,$(ObjectList))

.PHONY: all clean

all: $(OBJS)

%.rel: %.c
	$(SDCC) $(COMMON_FLAGS) $(SDCCFLAGS_$*) -c $<

clean:
	rm -f *.rel *.asm *.lst *.sym *.adb *.cdb *.ihx *.lk *.map *.mem *.noi *.omf *.rst *.s19
